// <auto-generated />
using System;
using BourseIA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BourseIA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422141429_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BourseIA.Models.CourbeBoursiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeAction")
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("CourbesBousieres");
                });

            modelBuilder.Entity("BourseIA.Models.IdeeInvestissement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionConcernee")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstPublique")
                        .HasColumnType("boolean");

                    b.Property<double?>("RentabiliteEstimee")
                        .HasColumnType("double precision");

                    b.Property<int?>("ResultatAnalyseId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Tendance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TypeIdee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResultatAnalyseId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("IdeesInvestissement");
                });

            modelBuilder.Entity("BourseIA.Models.MembreEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdhesion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("MembresEquipe");
                });

            modelBuilder.Entity("BourseIA.Models.MessageChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DestinataireId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstLu")
                        .HasColumnType("boolean");

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DestinataireId");

                    b.HasIndex("ExpediteurId");

                    b.HasIndex("TeamId");

                    b.ToTable("MessagesChat");
                });

            modelBuilder.Entity("BourseIA.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstLue")
                        .HasColumnType("boolean");

                    b.Property<string>("LienAction")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BourseIA.Models.PartageEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<int>("CourbeBoursiereId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatePartage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartageParId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourbeBoursiereId");

                    b.HasIndex("PartageParId");

                    b.HasIndex("TeamId");

                    b.ToTable("PartagesEquipe");
                });

            modelBuilder.Entity("BourseIA.Models.ResultatAnalyse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourbeBoursiereId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAnalyse")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EcartType")
                        .HasColumnType("double precision");

                    b.Property<string>("MessageErreur")
                        .HasColumnType("text");

                    b.Property<string>("PointsCles")
                        .HasColumnType("text");

                    b.Property<double?>("PrixMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("PrixMin")
                        .HasColumnType("double precision");

                    b.Property<double?>("PrixMoyen")
                        .HasColumnType("double precision");

                    b.Property<string>("RapportJson")
                        .HasColumnType("text");

                    b.Property<string>("StatutAnalyse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tendance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourbeBoursiereId")
                        .IsUnique();

                    b.ToTable("ResultatsAnalyse");
                });

            modelBuilder.Entity("BourseIA.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreateurId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("BourseIA.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoProfil")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfilInvestisseur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("BourseIA.Models.CourbeBoursiere", b =>
                {
                    b.HasOne("BourseIA.Models.Utilisateur", "Utilisateur")
                        .WithMany("Courbes")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BourseIA.Models.IdeeInvestissement", b =>
                {
                    b.HasOne("BourseIA.Models.ResultatAnalyse", "ResultatAnalyse")
                        .WithMany()
                        .HasForeignKey("ResultatAnalyseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BourseIA.Models.Team", "Team")
                        .WithMany("Idees")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BourseIA.Models.Utilisateur", "Utilisateur")
                        .WithMany("Idees")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultatAnalyse");

                    b.Navigation("Team");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BourseIA.Models.MembreEquipe", b =>
                {
                    b.HasOne("BourseIA.Models.Team", "Team")
                        .WithMany("Membres")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BourseIA.Models.Utilisateur", "Utilisateur")
                        .WithMany("Equipes")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BourseIA.Models.MessageChat", b =>
                {
                    b.HasOne("BourseIA.Models.Utilisateur", "Destinataire")
                        .WithMany()
                        .HasForeignKey("DestinataireId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BourseIA.Models.Utilisateur", "Expediteur")
                        .WithMany("MessagesEnvoyes")
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BourseIA.Models.Team", "Team")
                        .WithMany("Messages")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Destinataire");

                    b.Navigation("Expediteur");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BourseIA.Models.Notification", b =>
                {
                    b.HasOne("BourseIA.Models.Utilisateur", "Utilisateur")
                        .WithMany("Notifications")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BourseIA.Models.PartageEquipe", b =>
                {
                    b.HasOne("BourseIA.Models.CourbeBoursiere", "CourbeBoursiere")
                        .WithMany("Partages")
                        .HasForeignKey("CourbeBoursiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BourseIA.Models.Utilisateur", "PartagePar")
                        .WithMany()
                        .HasForeignKey("PartageParId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BourseIA.Models.Team", "Team")
                        .WithMany("Partages")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourbeBoursiere");

                    b.Navigation("PartagePar");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BourseIA.Models.ResultatAnalyse", b =>
                {
                    b.HasOne("BourseIA.Models.CourbeBoursiere", "CourbeBoursiere")
                        .WithOne("ResultatAnalyse")
                        .HasForeignKey("BourseIA.Models.ResultatAnalyse", "CourbeBoursiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourbeBoursiere");
                });

            modelBuilder.Entity("BourseIA.Models.Team", b =>
                {
                    b.HasOne("BourseIA.Models.Utilisateur", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("BourseIA.Models.CourbeBoursiere", b =>
                {
                    b.Navigation("Partages");

                    b.Navigation("ResultatAnalyse");
                });

            modelBuilder.Entity("BourseIA.Models.Team", b =>
                {
                    b.Navigation("Idees");

                    b.Navigation("Membres");

                    b.Navigation("Messages");

                    b.Navigation("Partages");
                });

            modelBuilder.Entity("BourseIA.Models.Utilisateur", b =>
                {
                    b.Navigation("Courbes");

                    b.Navigation("Equipes");

                    b.Navigation("Idees");

                    b.Navigation("MessagesEnvoyes");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
