apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coin-system.fullname" . }}-db-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "coin-system.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.credentials.username | quote }}
  password: {{ .Values.database.credentials.password | quote }}
  database: {{ .Values.database.credentials.database | quote }}

